apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 3000          # Port exposed by the service
      targetPort: 3000    # Port on the container
      nodePort: 30007      # Specify a NodePort or let Kubernetes assign one
